source1:
  host: 10.57.251.133
  username: data_reporteria
  port: 3306
  password: BCrcgRXI69l3
  database: miosv2-phone 
source3:
  host: 127.0.0.1
  username: bigdata_miguelhernandez 
  port: 3308
  password: o39296fAu5yf
  database: miosv2_ciu_etb
source2:
  token: 7129224963:AAHJS4qVFFpgyU6ALc6uEg5qtss0vV8VN_o
  chat_id: -1002146966812  
source4:
  host: 172.17.8.68
  username: miguelhernandez3067
  port: 3306
  password: ndBn8x4B!nP1VlQFFBX&
  database: bbdd_groupcos_repositorio_etb
source5:
  host: auroradb-montechelo.crowqa6ssn3h.us-east-1.rds.amazonaws.com
  username: bigdata_miguelhernandez 
  port: 3306
  password: o39296fAu5yf
  database: miosv2_ciu_etb

