source1:
  host: 172.17.8.176
  username: username1
  port: 3306
  password:
  database: miosv2-phone 
source3:
  host: 127.0.0.1
  username: username2 
  port: 3308
  password: 
  database: miosv2_ciu_etb
source2:
  token: token
  chat_id: chat_id
source4:
  host: 172.17.8.68
  username: username3
  port: 3306
  password: 
  database: bbdd_groupcos_repositorio_etb
source5:
  host: auroradb-montechelo.crowqa6ssn3h.us-east-1.rds.amazonaws.com
  username: username4 
  port: 3306
  password: 
  database: miosv2_ciu_etb
